/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/first-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create First User */
        post: operations["create_first_user_api_v1_admin_first_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/places/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Places */
        post: operations["import_places_api_v1_admin_places_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Access Token
         * @description OAuth2 compatible token login, get an access token for future requests
         */
        post: operations["login_access_token_api_v1_login_access_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Tokens */
        post: operations["refresh_tokens_api_v1_login_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Media */
        post: operations["upload_media_api_v1_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{media_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media Content */
        get: operations["get_media_content_api_v1_media__media_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode Places */
        get: operations["geocode_places_api_v1_places_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/reverse-geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse Geocode Places */
        get: operations["reverse_geocode_places_api_v1_places_reverse_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_v1_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip */
        patch: operations["update_trip_api_v1_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Itinerary */
        get: operations["get_itinerary_api_v1_trips__trip_id__itinerary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary/legs/{leg_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leg */
        get: operations["get_leg_api_v1_trips__trip_id__itinerary_legs__leg_id__get"];
        /** Replace Leg */
        put: operations["replace_leg_api_v1_trips__trip_id__itinerary_legs__leg_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary/legs/{leg_id}/route-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Leg Route */
        post: operations["refresh_leg_route_api_v1_trips__trip_id__itinerary_legs__leg_id__route_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stop */
        post: operations["create_stop_api_v1_trips__trip_id__itinerary_stops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/itinerary/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stop */
        get: operations["get_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__get"];
        put?: never;
        post?: never;
        /** Delete Stop */
        delete: operations["delete_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__delete"];
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trip Members */
        get: operations["list_trip_members_api_v1_trips__trip_id__members_get"];
        put?: never;
        /** Add Trip Member */
        post: operations["add_trip_member_api_v1_trips__trip_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Trip Member */
        delete: operations["remove_trip_member_api_v1_trips__trip_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip Member */
        patch: operations["update_trip_member_api_v1_trips__trip_id__members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_v1_trips__trip_id__posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_api_v1_trips__trip_id__posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_v1_trips__trip_id__posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_v1_trips__trip_id__posts__post_id__delete"];
        options?: never;
        head?: never;
        /** Update Post */
        patch: operations["update_post_api_v1_trips__trip_id__posts__post_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/posts/{post_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Post */
        post: operations["publish_post_api_v1_trips__trip_id__posts__post_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/posts/{post_id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish Post */
        post: operations["unpublish_post_api_v1_trips__trip_id__posts__post_id__unpublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/share-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Share Links */
        get: operations["list_share_links_api_v1_trips__trip_id__share_links_get"];
        put?: never;
        /** Create Share Link */
        post: operations["create_share_link_api_v1_trips__trip_id__share_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/share-links/{share_link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Share Link */
        delete: operations["revoke_share_link_api_v1_trips__trip_id__share_links__share_link_id__delete"];
        options?: never;
        head?: never;
        /** Update Share Link */
        patch: operations["update_share_link_api_v1_trips__trip_id__share_links__share_link_id__patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/viewers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trip Viewers */
        get: operations["list_trip_viewers_api_v1_trips__trip_id__viewers_get"];
        put?: never;
        /** Add Trip Viewer */
        post: operations["add_trip_viewer_api_v1_trips__trip_id__viewers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/viewers/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Trip Viewer */
        delete: operations["remove_trip_viewer_api_v1_trips__trip_id__viewers__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["search_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/by-username/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User By Username */
        get: operations["get_user_by_username_api_v1_users_by_username__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User */
        get: operations["read_user_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Profile */
        patch: operations["update_user_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/username-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Username Availability */
        get: operations["check_username_availability_api_v1_users_username_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User By Id */
        get: operations["get_user_by_id_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_access_token_api_v1_login_access_token_post */
        Body_login_access_token_api_v1_login_access_token_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_upload_media_api_v1_media_post */
        Body_upload_media_api_v1_media_post: {
            /** File */
            file: string;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            profile: components["schemas"]["UserProfileResponse"] | null;
            role: components["schemas"]["UserRole"];
        };
        /** FirstUserCreateRequest */
        FirstUserCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** FirstUserCreateResponse */
        FirstUserCreateResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** GeoJsonLineString */
        GeoJsonLineString: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][];
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageTechnicalInfo */
        ImageTechnicalInfo: {
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
        /** ItineraryPlacement */
        ItineraryPlacement: {
            /** After Stop Id */
            after_stop_id: string | null;
            /**
             * Planned Start Date
             * Format: date
             */
            planned_start_date: string;
        };
        /** ItineraryResponse */
        ItineraryResponse: {
            /** Itinerary Revision */
            itinerary_revision: number;
            /** Legs */
            legs: components["schemas"]["ItineraryTravelLegResponse"][];
            /** Stops */
            stops: components["schemas"]["ItineraryStopResponse"][];
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /**
         * ItineraryRouteType
         * @enum {string}
         */
        ItineraryRouteType: "PROVIDER_BACKED" | "SIMPLE";
        /** ItineraryStopCreateRequest */
        ItineraryStopCreateRequest: {
            incoming_travel?: components["schemas"]["ItineraryTravelReplaceRequest"] | null;
            /** Location */
            location: components["schemas"]["LocationPlaceInput"] | components["schemas"]["LocationCoordinatesInput"];
            /**
             * Notes
             * @default
             */
            notes: string;
            outgoing_travel?: components["schemas"]["ItineraryTravelReplaceRequest"] | null;
            placement: components["schemas"]["ItineraryPlacement"];
            /** Planned Nights */
            planned_nights: number;
            /** Title */
            title: string;
        };
        /** ItineraryStopDetailResponse */
        ItineraryStopDetailResponse: {
            incoming_leg: components["schemas"]["ItineraryTravelLegResponse"] | null;
            outgoing_leg: components["schemas"]["ItineraryTravelLegResponse"] | null;
            stop: components["schemas"]["ItineraryStopResponse"];
        };
        /** ItineraryStopResponse */
        ItineraryStopResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UserSummaryResponse"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            location: components["schemas"]["LocationResponse"];
            /** Notes */
            notes: string;
            /** Planned Nights */
            planned_nights: number;
            /**
             * Planned Start Date
             * Format: date
             */
            planned_start_date: string;
            /** Same Day Position */
            same_day_position: number;
            /** Title */
            title: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Visited */
            visited: boolean;
        };
        /** ItineraryStopUpdateRequest */
        ItineraryStopUpdateRequest: {
            incoming_travel?: components["schemas"]["ItineraryTravelReplaceRequest"] | null;
            /** Location */
            location?: components["schemas"]["LocationPlaceInput"] | components["schemas"]["LocationCoordinatesInput"] | null;
            /** Notes */
            notes?: string | null;
            outgoing_travel?: components["schemas"]["ItineraryTravelReplaceRequest"] | null;
            placement?: components["schemas"]["ItineraryPlacement"] | null;
            /** Planned Nights */
            planned_nights?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ItineraryTravelLegResponse */
        ItineraryTravelLegResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * From Stop Id
             * Format: uuid
             */
            from_stop_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string;
            /** Operator */
            operator: string | null;
            /** Reference */
            reference: string | null;
            route: components["schemas"]["ItineraryTravelRouteResponse"];
            /**
             * To Stop Id
             * Format: uuid
             */
            to_stop_id: string;
            travel_mode: components["schemas"]["TravelMode"];
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ItineraryTravelReplaceRequest */
        ItineraryTravelReplaceRequest: {
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Operator */
            operator?: string | null;
            /** Reference */
            reference?: string | null;
            travel_mode: components["schemas"]["TravelMode"];
        };
        /** ItineraryTravelRouteResponse */
        ItineraryTravelRouteResponse: {
            /** Distance Meters */
            distance_meters: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            geometry: components["schemas"]["GeoJsonLineString"];
            type: components["schemas"]["ItineraryRouteType"];
        };
        /** LocationCoordinatesInput */
        LocationCoordinatesInput: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LocationPlaceInput */
        LocationPlaceInput: {
            /**
             * Place Id
             * Format: uuid
             */
            place_id: string;
        };
        /** LocationResponse */
        LocationResponse: {
            /** Country Code */
            country_code: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Region */
            region: string;
        };
        /** MediaMetadata */
        MediaMetadata: {
            /** Caption */
            caption: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MediaResponse */
        MediaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "IMAGE" | "VIDEO";
            metadata: components["schemas"]["MediaMetadata"];
            /**
             * Status
             * @enum {string}
             */
            status: "UPLOADED" | "READY" | "FAILED";
            /** Technical Info */
            technical_info: components["schemas"]["ImageTechnicalInfo"] | components["schemas"]["VideoTechnicalInfo"] | null;
            urls: components["schemas"]["MediaUrls"];
        };
        /** MediaUploadResponse */
        MediaUploadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** MediaUrls */
        MediaUrls: {
            /** Content */
            content: string;
            /** Thumbnail */
            thumbnail: string | null;
        };
        /** PaginatedResponse[PostResponse] */
        PaginatedResponse_PostResponse_: {
            /** Items */
            items: components["schemas"]["PostResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PaginatedResponse[TripResponse] */
        PaginatedResponse_TripResponse_: {
            /** Items */
            items: components["schemas"]["TripResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PaginatedResponse[UserSummaryResponse] */
        PaginatedResponse_UserSummaryResponse_: {
            /** Items */
            items: components["schemas"]["UserSummaryResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PlaceImportRequest */
        PlaceImportRequest: {
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "cities500" | "allCountries";
            /**
             * Replace Existing
             * @default false
             */
            replace_existing: boolean;
        };
        /** PlaceImportResponse */
        PlaceImportResponse: {
            /**
             * Dataset
             * @enum {string}
             */
            dataset: "cities500" | "allCountries";
            /** Deleted */
            deleted: number;
            /** Processed */
            processed: number;
        };
        /** PlaceResponse */
        PlaceResponse: {
            /** Country Code */
            country_code: string;
            /** Feature Class */
            feature_class: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Population */
            population: number;
            /** Region */
            region: string;
        };
        /** PostCreateRequest */
        PostCreateRequest: {
            /** Body */
            body: string;
            /** Location */
            location: components["schemas"]["LocationPlaceInput"] | components["schemas"]["LocationCoordinatesInput"];
            /** Media Ids */
            media_ids?: string[];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Publish
             * @default false
             */
            publish: boolean;
            /** Title */
            title: string;
        };
        /** PostResponse */
        PostResponse: {
            author: components["schemas"]["UserSummaryResponse"];
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            location: components["schemas"]["LocationResponse"];
            /** Media */
            media: components["schemas"]["MediaResponse"][];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Published At */
            published_at: string | null;
            /** Title */
            title: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PostSortField
         * @enum {string}
         */
        PostSortField: "occurred_at" | "published_at" | "created_at" | "updated_at";
        /**
         * PostStatusFilter
         * @enum {string}
         */
        PostStatusFilter: "published" | "draft" | "all";
        /** PostUpdateRequest */
        PostUpdateRequest: {
            /** Body */
            body?: string | null;
            /** Location */
            location?: components["schemas"]["LocationPlaceInput"] | components["schemas"]["LocationCoordinatesInput"] | null;
            /** Media Ids */
            media_ids?: string[] | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Title */
            title?: string | null;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReverseGeocodeResponse */
        ReverseGeocodeResponse: {
            /** Distance Km */
            distance_km: number;
            place: components["schemas"]["PlaceResponse"];
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Id Token */
            id_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TravelMode
         * @enum {string}
         */
        TravelMode: "UNKNOWN" | "WALK" | "BIKE" | "CAR" | "BUS" | "TRAIN" | "FERRY" | "FLIGHT" | "OTHER";
        /** TripCreateRequest */
        TripCreateRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Media Id
             * Format: uuid
             */
            media_id: string;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** @default PRIVATE */
            visibility: components["schemas"]["TripVisibility"];
        };
        /** TripMemberCreateRequest */
        TripMemberCreateRequest: {
            /** @default MEMBER */
            role: components["schemas"]["TripRole"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TripMemberResponse */
        TripMemberResponse: {
            role: components["schemas"]["TripRole"];
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            user: components["schemas"]["UserSummaryResponse"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TripMemberUpdateRequest */
        TripMemberUpdateRequest: {
            role: components["schemas"]["TripRole"];
        };
        /** TripResponse */
        TripResponse: {
            cover_media: components["schemas"]["MediaResponse"] | null;
            /** Description */
            description: string;
            /** End Date */
            end_date: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            visibility: components["schemas"]["TripVisibility"];
        };
        /**
         * TripRole
         * @enum {string}
         */
        TripRole: "OWNER" | "MEMBER";
        /** TripShareLinkCreateRequest */
        TripShareLinkCreateRequest: {
            /** Expires At */
            expires_at?: string | null;
            /** Label */
            label?: string | null;
        };
        /** TripShareLinkCreateResponse */
        TripShareLinkCreateResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Token */
            token: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /** TripShareLinkResponse */
        TripShareLinkResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
        };
        /** TripShareLinkUpdateRequest */
        TripShareLinkUpdateRequest: {
            /** Expires At */
            expires_at?: string | null;
            /** Label */
            label?: string | null;
            /** Revoked */
            revoked?: boolean | null;
        };
        /**
         * TripSortField
         * @enum {string}
         */
        TripSortField: "start_date" | "created_at" | "updated_at" | "name";
        /**
         * TripStatusFilter
         * @enum {string}
         */
        TripStatusFilter: "all" | "ongoing" | "upcoming" | "past";
        /** TripUpdateRequest */
        TripUpdateRequest: {
            /** Description */
            description?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Media Id */
            media_id?: string | null;
            /** Name */
            name?: string | null;
            /** Start Date */
            start_date?: string | null;
            visibility?: components["schemas"]["TripVisibility"] | null;
        };
        /** TripViewerCreateRequest */
        TripViewerCreateRequest: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TripViewerResponse */
        TripViewerResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            user: components["schemas"]["UserSummaryResponse"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * TripVisibility
         * @enum {string}
         */
        TripVisibility: "PUBLIC" | "PLATFORM_PUBLIC" | "PRIVATE";
        /** UserProfileResponse */
        UserProfileResponse: {
            /** Biography */
            biography: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            profile_picture: components["schemas"]["MediaResponse"] | null;
            /** Profile Picture Media Id */
            profile_picture_media_id: string | null;
            /** Username */
            username: string;
        };
        /** UserProfileUpdateRequest */
        UserProfileUpdateRequest: {
            /** Biography */
            biography?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Profile Picture Media Id */
            profile_picture_media_id?: string | null;
            /** Username */
            username?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            profile: components["schemas"]["UserProfileResponse"] | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "USER" | "ADMIN";
        /** UserSummaryResponse */
        UserSummaryResponse: {
            /** First Name */
            first_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string | null;
            /** Username */
            username: string | null;
        };
        /** UsernameAvailabilityResponse */
        UsernameAvailabilityResponse: {
            /** Available */
            available: boolean;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: unknown[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoTechnicalInfo */
        VideoTechnicalInfo: {
            /** Duration */
            duration: number;
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_first_user_api_v1_admin_first_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirstUserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirstUserCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_places_api_v1_admin_places_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_access_token_api_v1_login_access_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_api_v1_login_access_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tokens_api_v1_login_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_api_v1_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_api_v1_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_content_api_v1_media__media_id__content_get: {
        parameters: {
            query?: {
                thumbnail?: boolean;
                media_token?: string | null;
            };
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_places_api_v1_places_geocode_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
                country_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_geocode_places_api_v1_places_reverse_geocode_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                limit?: number;
                max_distance_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseGeocodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                sort_by?: components["schemas"]["TripSortField"];
                sort_order?: components["schemas"]["SortDirection"];
                status?: components["schemas"]["TripStatusFilter"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TripResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_v1_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_v1_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_api_v1_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_itinerary_api_v1_trips__trip_id__itinerary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leg_api_v1_trips__trip_id__itinerary_legs__leg_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
                leg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryTravelLegResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_leg_api_v1_trips__trip_id__itinerary_legs__leg_id__put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
                leg_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryTravelReplaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryTravelLegResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_leg_route_api_v1_trips__trip_id__itinerary_legs__leg_id__route_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                leg_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryTravelLegResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stop_api_v1_trips__trip_id__itinerary_stops_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryStopCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryStopDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_api_v1_trips__trip_id__itinerary_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                trip_id: string;
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryStopUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trip_members_api_v1_trips__trip_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripMemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_trip_member_api_v1_trips__trip_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripMemberCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_trip_member_api_v1_trips__trip_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_member_api_v1_trips__trip_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripMemberUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_api_v1_trips__trip_id__posts_get: {
        parameters: {
            query?: {
                sort_by?: components["schemas"]["PostSortField"];
                sort_order?: components["schemas"]["SortDirection"];
                status?: components["schemas"]["PostStatusFilter"];
                page?: number;
                page_size?: number;
            };
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PostResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_v1_trips__trip_id__posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_v1_trips__trip_id__posts__post_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Trip-Share-Token"?: string | null;
            };
            path: {
                trip_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_v1_trips__trip_id__posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_v1_trips__trip_id__posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_post_api_v1_trips__trip_id__posts__post_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_post_api_v1_trips__trip_id__posts__post_id__unpublish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_share_links_api_v1_trips__trip_id__share_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripShareLinkResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_link_api_v1_trips__trip_id__share_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripShareLinkCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripShareLinkCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_share_link_api_v1_trips__trip_id__share_links__share_link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                share_link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_share_link_api_v1_trips__trip_id__share_links__share_link_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                share_link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripShareLinkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripShareLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trip_viewers_api_v1_trips__trip_id__viewers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripViewerResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_trip_viewer_api_v1_trips__trip_id__viewers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripViewerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripViewerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_trip_viewer_api_v1_trips__trip_id__viewers__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_users_api_v1_users_get: {
        parameters: {
            query: {
                query: string;
                exclude_current_user?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_UserSummaryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_by_username_api_v1_users_by_username__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    update_user_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_username_availability_api_v1_users_username_availability_get: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameAvailabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_by_id_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
