"""stricter things for planned travel

Revision ID: 039e3c5a7c6b
Revises: 28ea06ff5086
Create Date: 2026-07-05 09:54:17.687368+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e3c5a7c6b'
down_revision: Union[str, Sequence[str], None] = '28ea06ff5086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_planned_steps_trip_id_id', 'planned_steps', ['trip_id', 'id'])
    op.drop_constraint(op.f('fk_planned_travel_to_planned_step_id'), 'planned_travel', type_='foreignkey')
    op.drop_constraint(op.f('fk_planned_travel_from_planned_step_id'), 'planned_travel', type_='foreignkey')
    op.create_foreign_key('fk_planned_travel_trip_to_planned_step_id', 'planned_travel', 'planned_steps', ['trip_id', 'to_planned_step_id'], ['trip_id', 'id'], ondelete='CASCADE')
    op.create_foreign_key('fk_planned_travel_trip_from_planned_step_id', 'planned_travel', 'planned_steps', ['trip_id', 'from_planned_step_id'], ['trip_id', 'id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_planned_travel_trip_from_planned_step_id', 'planned_travel', type_='foreignkey')
    op.drop_constraint('fk_planned_travel_trip_to_planned_step_id', 'planned_travel', type_='foreignkey')
    op.create_foreign_key(op.f('fk_planned_travel_from_planned_step_id'), 'planned_travel', 'planned_steps', ['from_planned_step_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_planned_travel_to_planned_step_id'), 'planned_travel', 'planned_steps', ['to_planned_step_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_planned_steps_trip_id_id', 'planned_steps', type_='unique')
    # ### end Alembic commands ###
