"""things again

Revision ID: 775c052be5d5
Revises: 60ea4dc64d60
Create Date: 2026-06-28 22:12:04.590958+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775c052be5d5'
down_revision: Union[str, Sequence[str], None] = '60ea4dc64d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_locations_created_by', 'locations', ['created_by'], unique=False)
    op.create_index('ix_locations_trip_id', 'locations', ['trip_id'], unique=False)
    op.create_index('ix_planned_steps_location_id', 'planned_steps', ['location_id'], unique=False)
    op.create_index('ix_planned_steps_trip_id_step_number', 'planned_steps', ['trip_id', 'step_number'], unique=False)
    op.create_foreign_key('fk_planned_steps_location_id', 'planned_steps', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_planned_travel_trip_from_to', 'planned_travel', ['trip_id', 'from_planned_step_id', 'to_planned_step_id'], unique=False)
    op.create_foreign_key('fk_planned_travel_to_planned_step_id', 'planned_travel', 'planned_steps', ['to_planned_step_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_planned_travel_from_planned_step_id', 'planned_travel', 'planned_steps', ['from_planned_step_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_posts_author_user_id', 'posts', ['author_user_id'], unique=False)
    op.create_index('ix_posts_location_id', 'posts', ['location_id'], unique=False)
    op.create_index('ix_posts_trip_id_published_at', 'posts', ['trip_id', 'published_at'], unique=False)
    op.create_foreign_key('fk_posts_location_id', 'posts', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_posts_location_id', 'posts', type_='foreignkey')
    op.drop_index('ix_posts_trip_id_published_at', table_name='posts')
    op.drop_index('ix_posts_location_id', table_name='posts')
    op.drop_index('ix_posts_author_user_id', table_name='posts')
    op.drop_constraint('fk_planned_travel_from_planned_step_id', 'planned_travel', type_='foreignkey')
    op.drop_constraint('fk_planned_travel_to_planned_step_id', 'planned_travel', type_='foreignkey')
    op.drop_index('ix_planned_travel_trip_from_to', table_name='planned_travel')
    op.drop_constraint('fk_planned_steps_location_id', 'planned_steps', type_='foreignkey')
    op.drop_index('ix_planned_steps_trip_id_step_number', table_name='planned_steps')
    op.drop_index('ix_planned_steps_location_id', table_name='planned_steps')
    op.drop_index('ix_locations_trip_id', table_name='locations')
    op.drop_index('ix_locations_created_by', table_name='locations')
    # ### end Alembic commands ###
