"""initial version

Revision ID: a109e51f3065
Revises: 
Create Date: 2026-05-02 19:47:27.576752+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a109e51f3065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=255), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_storage_path', sa.String(length=2048), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_content_type', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True, comment='Applicable for images and videos, represents the width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Applicable for images and videos, represents the height in pixels'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duration in seconds, applicable for videos'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_media_created_by', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('visibility', sa.String(length=32), server_default='PRIVATE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], name='fk_trips_cover_media_id', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_cover_media_id'), 'trips', ['cover_media_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('fk_user_profiles_user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('profile_picture_media_id', sa.Uuid(), nullable=True),
    sa.Column('biography', sa.String(length=2048), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_profiles_user_id'], ['users.id'], name='fk_user_profiles_user_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_picture_media_id'], ['media.id'], name='fk_user_profiles_profile_picture_media_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('fk_user_profiles_user_id')
    )
    op.create_index(op.f('ix_user_profiles_profile_picture_media_id'), 'user_profiles', ['profile_picture_media_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_slug'), 'user_profiles', ['slug'], unique=True)
    op.create_table('trip_members',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_trip_members_trip_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_trip_members_user_id'),
    sa.PrimaryKeyConstraint('trip_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_members')
    op.drop_index(op.f('ix_user_profiles_slug'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_picture_media_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trips_cover_media_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
