"""regenerate migrations

Revision ID: a2e88e4b08ba
Revises: 
Create Date: 2026-07-04 09:49:04.822572+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e88e4b08ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(precision=53), nullable=False),
    sa.Column('longitude', sa.Float(precision=53), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('feature_class', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_places_external_source_external_id')
    )
    op.create_index('ix_places_country_code_region', 'places', ['country_code', 'region'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=255), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_storage_path', sa.String(length=2048), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_content_type', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True, comment='Applicable for images and videos, represents the width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Applicable for images and videos, represents the height in pixels'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duration in seconds, applicable for videos'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_media_created_by', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('visibility', sa.String(length=32), server_default='PRIVATE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], name='fk_trips_cover_media_id', ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_cover_media_id'), 'trips', ['cover_media_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_media_id', sa.Uuid(), nullable=True),
    sa.Column('biography', sa.String(length=2048), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_picture_media_id'], ['media.id'], name='fk_user_profiles_profile_picture_media_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_profiles_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_profile_picture_media_id'), 'user_profiles', ['profile_picture_media_id'], unique=False)
    op.create_index('ix_user_profiles_username', 'user_profiles', [sa.literal_column("lower(regexp_replace(username, '[-._]', '', 'g'))")], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(precision=53), nullable=False),
    sa.Column('longitude', sa.Float(precision=53), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_locations_created_by'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_locations_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_created_by', 'locations', ['created_by'], unique=False)
    op.create_index('ix_locations_trip_id', 'locations', ['trip_id'], unique=False)
    op.create_table('trip_members',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_trip_members_trip_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_trip_members_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'user_id')
    )
    op.create_table('planned_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_planned_steps_location_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_planned_steps_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planned_steps_location_id', 'planned_steps', ['location_id'], unique=False)
    op.create_index('ix_planned_steps_trip_id_step_number', 'planned_steps', ['trip_id', 'step_number'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name='fk_posts_author_user_id'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_posts_location_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_posts_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author_user_id', 'posts', ['author_user_id'], unique=False)
    op.create_index('ix_posts_location_id', 'posts', ['location_id'], unique=False)
    op.create_index('ix_posts_trip_id_occurred_at', 'posts', ['trip_id', 'occurred_at'], unique=False)
    op.create_index('ix_posts_trip_id_published_at', 'posts', ['trip_id', 'published_at'], unique=False)
    op.create_table('planned_travel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('from_planned_step_id', sa.Uuid(), nullable=False),
    sa.Column('to_planned_step_id', sa.Uuid(), nullable=False),
    sa.Column('travel_mode', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_planned_step_id <> to_planned_step_id', name='ck_planned_travel_distinct_steps'),
    sa.ForeignKeyConstraint(['from_planned_step_id'], ['planned_steps.id'], name='fk_planned_travel_from_planned_step_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_planned_step_id'], ['planned_steps.id'], name='fk_planned_travel_to_planned_step_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_planned_travel_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planned_travel_trip_from_to', 'planned_travel', ['trip_id', 'from_planned_step_id', 'to_planned_step_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='fk_post_media_media_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_media_post_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'media_id', name='uq_post_media_post_id_media_id')
    )
    op.create_index('ix_post_media_media_id', 'post_media', ['media_id'], unique=False)
    op.create_index('ix_post_media_post_id_sort_order', 'post_media', ['post_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_media_post_id_sort_order', table_name='post_media')
    op.drop_index('ix_post_media_media_id', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('ix_planned_travel_trip_from_to', table_name='planned_travel')
    op.drop_table('planned_travel')
    op.drop_index('ix_posts_trip_id_published_at', table_name='posts')
    op.drop_index('ix_posts_trip_id_occurred_at', table_name='posts')
    op.drop_index('ix_posts_location_id', table_name='posts')
    op.drop_index('ix_posts_author_user_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_planned_steps_trip_id_step_number', table_name='planned_steps')
    op.drop_index('ix_planned_steps_location_id', table_name='planned_steps')
    op.drop_table('planned_steps')
    op.drop_table('trip_members')
    op.drop_index('ix_locations_trip_id', table_name='locations')
    op.drop_index('ix_locations_created_by', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_user_profiles_username', table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_picture_media_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trips_cover_media_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_places_country_code_region', table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
