"""placse updated

Revision ID: aae1916b09e6
Revises: 5e528c4874e8
Create Date: 2026-06-27 18:06:55.008034+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae1916b09e6'
down_revision: Union[str, Sequence[str], None] = '5e528c4874e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('external_source', sa.String(length=64), nullable=False))
    op.add_column('places', sa.Column('external_id', sa.String(length=64), nullable=False))
    op.add_column('places', sa.Column('search_name', sa.String(length=255), nullable=False))
    op.add_column('places', sa.Column('feature_class', sa.String(length=1), nullable=False))
    op.add_column('places', sa.Column('feature_code', sa.String(length=16), nullable=False))
    op.add_column('places', sa.Column('population', sa.Integer(), server_default='0', nullable=False))
    op.add_column('places', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('places', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_places_country_code_region', 'places', ['country_code', 'region'], unique=False)
    op.create_index('ix_places_search_name', 'places', ['search_name'], unique=False)
    op.create_unique_constraint('uq_places_external_source_external_id', 'places', ['external_source', 'external_id'])
    op.drop_column('post_media', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('visibility', sa.VARCHAR(length=32), server_default=sa.text("'PUBLIC'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_places_external_source_external_id', 'places', type_='unique')
    op.drop_index('ix_places_search_name', table_name='places')
    op.drop_index('ix_places_country_code_region', table_name='places')
    op.drop_column('places', 'updated_at')
    op.drop_column('places', 'created_at')
    op.drop_column('places', 'population')
    op.drop_column('places', 'feature_code')
    op.drop_column('places', 'feature_class')
    op.drop_column('places', 'search_name')
    op.drop_column('places', 'external_id')
    op.drop_column('places', 'external_source')
    # ### end Alembic commands ###
