"""new intinerary system

Revision ID: c394c2ff7a4d
Revises: 039e3c5a7c6b
Create Date: 2026-07-14 20:44:11.584744+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c394c2ff7a4d'
down_revision: Union[str, Sequence[str], None] = '039e3c5a7c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_locations_trip_id_id', 'locations', ['trip_id', 'id'])
    op.create_table('itinerary_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('same_day_position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('planned_nights', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_nights >= 0', name='ck_itinerary_stops_planned_nights_nonnegative'),
    sa.CheckConstraint('same_day_position >= 0', name='ck_itinerary_stops_same_day_position_nonnegative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_itinerary_stops_created_by'),
    sa.ForeignKeyConstraint(['trip_id', 'location_id'], ['locations.trip_id', 'locations.id'], name='fk_itinerary_stops_trip_location_id'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_itinerary_stops_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'id', name='uq_itinerary_stops_trip_id_id'),
    sa.UniqueConstraint('trip_id', 'planned_start_date', 'same_day_position', deferrable=True, initially='DEFERRED', name='uq_itinerary_stops_trip_date_position')
    )
    op.create_index('ix_itinerary_stops_created_by', 'itinerary_stops', ['created_by'], unique=False)
    op.create_index('ix_itinerary_stops_trip_date_position', 'itinerary_stops', ['trip_id', 'planned_start_date', 'same_day_position'], unique=False)
    op.create_index('ix_itinerary_stops_trip_location_id', 'itinerary_stops', ['trip_id', 'location_id'], unique=False)
    op.create_table('itinerary_travel_legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('from_stop_id', sa.Uuid(), nullable=False),
    sa.Column('to_stop_id', sa.Uuid(), nullable=False),
    sa.Column('travel_mode', sa.String(length=32), server_default='UNKNOWN', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_stop_id <> to_stop_id', name='ck_itinerary_travel_legs_distinct_stops'),
    sa.ForeignKeyConstraint(['trip_id', 'from_stop_id'], ['itinerary_stops.trip_id', 'itinerary_stops.id'], name='fk_itinerary_travel_legs_trip_from_stop_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id', 'to_stop_id'], ['itinerary_stops.trip_id', 'itinerary_stops.id'], name='fk_itinerary_travel_legs_trip_to_stop_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_itinerary_travel_legs_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'from_stop_id', name='uq_itinerary_travel_legs_trip_from_stop_id'),
    sa.UniqueConstraint('trip_id', 'to_stop_id', name='uq_itinerary_travel_legs_trip_to_stop_id')
    )
    op.drop_index(op.f('ix_planned_travel_trip_from_to'), table_name='planned_travel')
    op.drop_table('planned_travel')
    op.drop_index(op.f('ix_planned_steps_location_id'), table_name='planned_steps')
    op.drop_index(op.f('ix_planned_steps_trip_id_position'), table_name='planned_steps')
    op.drop_table('planned_steps')
    op.add_column('trips', sa.Column('itinerary_revision', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'itinerary_revision')
    op.drop_constraint('uq_locations_trip_id_id', 'locations', type_='unique')
    op.create_table('planned_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('departure_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_planned_steps_location_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_planned_steps_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('planned_steps_pkey')),
    sa.UniqueConstraint('trip_id', 'id', name=op.f('uq_planned_steps_trip_id_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_planned_steps_trip_id_position'), 'planned_steps', ['trip_id', 'position'], unique=True)
    op.create_index(op.f('ix_planned_steps_location_id'), 'planned_steps', ['location_id'], unique=False)
    op.create_table('planned_travel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_planned_step_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('to_planned_step_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('travel_mode', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('from_planned_step_id <> to_planned_step_id', name=op.f('ck_planned_travel_distinct_steps')),
    sa.ForeignKeyConstraint(['trip_id', 'from_planned_step_id'], ['planned_steps.trip_id', 'planned_steps.id'], name=op.f('fk_planned_travel_trip_from_planned_step_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id', 'to_planned_step_id'], ['planned_steps.trip_id', 'planned_steps.id'], name=op.f('fk_planned_travel_trip_to_planned_step_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_planned_travel_trip_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('planned_travel_pkey'))
    )
    op.create_index(op.f('ix_planned_travel_trip_from_to'), 'planned_travel', ['trip_id', 'from_planned_step_id', 'to_planned_step_id'], unique=True)
    op.drop_table('itinerary_travel_legs')
    op.drop_index('ix_itinerary_stops_trip_location_id', table_name='itinerary_stops')
    op.drop_index('ix_itinerary_stops_trip_date_position', table_name='itinerary_stops')
    op.drop_index('ix_itinerary_stops_created_by', table_name='itinerary_stops')
    op.drop_table('itinerary_stops')
    # ### end Alembic commands ###
